### ISSUE TITLE
Send kill signal to workers

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/UnstructuredData#180] opened 2017-04-22 19:03 UTC
When finished processing a batch, the master should send a kill signal to the workers OR append a `&& shutdown 0` to the worker after completing the script which batch processes the WAR files.

** please also check: does `shutdown 0` actually **undeploy** the machine? This you can check in a very naïve way by: calling `shutdown 0` on any worker, looking at the azure portal what it says for that machine: it should give you the option to _start_ the machine and there should be no warning of the type ![](https://files.gitter.im/MusicConnectionMachine/UnstructuredData/3nBK/Screen-Shot-2017-04-22-at-10.31.23.png)

**Comment by lgfrbcsgo** [comment] 2017-04-22 19:12
Our app already terminates when all work has been done. All processes will exit in a nicely manner. 

Well test auto shutdown tomorrow.

**Comment by sacdallago** [comment] 2017-04-22 19:54
yeah sure the app terminates, but no the VM on which it is running :) that is money

**Comment by lukasstreit** [comment] 2017-04-23 19:45
This **does not** work, I tried it out.
We can instead use a script that runs something like "az vm undeploy ..." for each vm once the processing is finished. This would have to be done manually though. 

We might also be able to write a script that regularly checks queue size and runs the command once the queue is empty.

**Comment by lgfrbcsgo** [comment] 2017-04-23 20:39
> We might also be able to write a script that regularly checks queue size and runs the command once the queue is empty.

Workers don't remove items from the queue immediately though. They just set an item to invisible for 30 minutes and only remove it if they've finished processing it.
So the question is, will the queue be shown empty when there a still items which are set to invisible?

**Comment by lukasstreit** [comment] 2017-04-23 20:47
Good point. We should stick with with manual shutdown for now in my opinion. 
[progress-checker.js](https://github.com/MusicConnectionMachine/UnstructuredData/blob/develop/scripts/queue-ops/progress-checker.js) can be used to check how far along our processing is.

**Comment by lgfrbcsgo** [comment] 2017-04-23 20:56
We should still add `&& shutdown 0` though. That way we only pay for the hardware and not the usage as well? It'll also indicate, that a worker has finished.

**Comment by pfent** [comment] 2017-04-23 20:56
uhm, might sound crazy, but:
Couldn't a VM undeploy itself with `az vm undeploy` once it is finished? Might be worth just trying that on a separate VM for 💩 and 😆 …

**Comment by lukasstreit** [comment] 2017-04-23 21:43
I had that thought as well but to me the problem is that the az commands require you to manually follow a login link and enter a code to login.. 
I didn't have any ideas yet about how to circumvent that :(
Otherwise it would probably be possible

**Comment by kordianbruck** [comment] 2017-04-24 01:34
As we changed to the queue, this should be less of a problem? 

A worker will work till theres no work left. The case of previously idle workers will happen like almost never. We just need a cleanup routine that undeploys everything once the queue is empty.

**Comment by lgfrbcsgo** [comment] 2017-04-24 10:12
> [...] once the queue is empty.

Well, as I wrote earlier, we should test what "empty" means. Does it mean there are no items at all in the queue or does it mean there are no visible items left. Workers set queue items to invisible for 30 minutes and only really remove it if they've offloaded everything to the storage / DB.

**Comment by felixschorer** [comment] 2017-04-27 17:23
Now, that we have queue monitoring implemented, we can close this.

**Closed by felixschorer** 2017-04-27 17:23 UTC
Labels: enhancement, high priority
