### ISSUE TITLE
DB access parameters have no effect right now!

### ISSUE THREAD

**Issue by lgfrbcsgo** [MusicConnectionMachine/UnstructuredData#133] opened 2017-04-11 19:17 UTC
`Storer` and `TermLoader` both don't take the DB access parameters into account.

**Comment by nyxathid** [comment] 2017-04-12 10:03
Fixed in the stable code (before refactoring PR #132). Also found a new BUG in `Storer`, see #134.

**Comment by nyxathid** [comment] 2017-04-13 00:04
was intended to be fixed in #135, #137 but finally only #139 mady it so far
anyway, its fixed

**Closed by nyxathid** 2017-04-13 00:04 UTC
Labels: bug, VERY HIGH Priority
